### ISSUE TITLE
Newport Design System will only work on node.js ver. 10.16.1 

### ISSUE THREAD

**Issue by jmakalinao** [vlocityinc/newport-design-system#30]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

-No screenshots needed, issue can be replicated. 

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

-I tried installing newport and got the error messages
-checked on similar reported issue - https://github.com/nodejs/node-gyp/issues/1694 but could not find a resolution.
-I tried installing the lower version of node.js (10.16.0), ran the install again and was able to launch it without errors.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

-issue related to installation of newport design system

> Are any specific browsers impacted by this bug?

-not applicable

> Which version of the Salesforce Lightning Design System are you using?

-not applicable. trying to install newport in laptop. 

> What steps and/or code are needed to reproduce this issue?

-install newport using the newest version of node.js 

> What did you expect to happen?

-should be able to install and launch newport design system

> What actually happened?

-gets an error message when higher version of node.js is installed

install fails with errors.
10 warnings and 8 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/Users/ekutepov/work_code/newport/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:203:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.6.0/bin/node" "/Users/ekutepov/work_code/newport/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/ekutepov/work_code/newport/node_modules/node-sass
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.0 postinstall script.

**Comment by mattgoldspink** [comment]
Hi @jmakalinao - Can you try with the code in the `ins-106.0` branch. We've made a number of changes to simplify dependencies so hopefully this should be resolved now.

**Comment by ivanovivelin** [comment]
@mattgoldspink running `npm install` under that branch seems to resolve it, but running `npm start` after that is causing the following error: 

<img width="860" alt="Screenshot 2019-11-11 at 13 38 05" src="https://user-images.githubusercontent.com/22252962/68589131-7057f800-048b-11ea-9a9d-88c3eeced4a7.png">

**Comment by mattgoldspink** [comment]
I believe this is fixed now. There was a problem with the older version of gulp we were using, which I've now upgrade. If you sync up #master then re-run npm install it should work.
