### ISSUE TITLE
npm run build removing the svg css changes.

### ISSUE THREAD

**Issue by paramesh-anakapalli** [vlocityinc/newport-design-system#37]
When we trying to override the SVG spinner styles like this

`.via-nds .nds-spinner svg circle:nth-child(1) {
  cx: 12.5%;
}
.via-nds .nds-spinner svg circle:nth-child(2) {
  cx: 50%;
}
.via-nds .nds-spinner svg circle:nth-child(3) {
  cx: 87.5%;
}`

and then run build command ( npm run build && npm run dist ) to generate min.css file; we are missing these above SVG changes in the generated CSS file.
cc: @mattgoldspink

**Comment by mattgoldspink** [comment]
This is a limitation with https://github.com/jakubpawlowicz/clean-css which is used for minifying the files. The workaround is to exclude the properties from being processed by clean-css. To do this surround them with the clean-css ignore comments:

```
.nds-spinner svg circle:nth-child(1) {
  /* clean-css ignore:start */
  cx: 12.5%;
  /* clean-css ignore:end */
}
```

Related ticket in clean-css: https://github.com/jakubpawlowicz/clean-css/issues/1021 for
