### ISSUE TITLE
Repository out of date

### ISSUE THREAD

**Issue by dayrontbs12001** [vlocityinc/newport-design-system#41]
I noticed that this repository is not up to date. Vlocity Newport Design System is at version 230.0.0 and this is 108. Can you please update the repository?

**Comment by rohanshenoy96** [comment]
Hi @dayrontbs12001. I'm facing the same issue. From where can I get the latest repository?

**Comment by mattgoldspink** [comment]
Hi @rohanshenoy96 - You can always get the latest code from the version branch of the product you're on. For example our latest 230 release is here: https://github.com/vlocityinc/newport-design-system/tree/230

We used to do different versions across industry packages, so for comms, media and energy older release would be under the respective branches for each:

- https://github.com/vlocityinc/newport-design-system/tree/cme-109.0
- https://github.com/vlocityinc/newport-design-system/tree/ins-109.0

Going forwards the versions will be the same for both products

Let me know if you've any further questions
