### ISSUE TITLE
Getting Syntax error on "npm install"

### ISSUE THREAD

**Issue by kirankapila** [vlocityinc/newport-design-system#43]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![image](https://user-images.githubusercontent.com/29833210/117986853-55668c80-b37d-11eb-884b-714e84c2fa81.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?
As it appears from the output, it appears to be a bug when installing dependencies using "npm install"

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

No
> Are any specific browsers impacted by this bug?

No
> Which version of the Salesforce Lightning Design System are you using?

NA. Issue happening when trying to setup NDS(New port design system) to run in storybook.

->

> What steps and/or code are needed to reproduce this issue?
[2021-05-12T13_36_42_756Z-debug.log](https://github.com/vlocityinc/newport-design-system/files/6466662/2021-05-12T13_36_42_756Z-debug.log)

Attached are the steps.  (npm version 7.11.2;  python 3.9.5; git 2.31.1; Windows 10 64-bit

> What did you expect to happen?
all dependencies installed without issues

> What actually happened?
dependencies not installed and npm_modules folder got deleted[](url)

**Comment by mattgoldspink** [comment]
Hi @kirankapila - it looks like you're hitting this issue: https://github.com/sass/node-sass/issues/3106

For now would it be possible for you to downgrade to Node 14 until we can test with Node 16 and verify that node-sass and other dependencies work as expected?

**Comment by kirankapila** [comment]
Thanks for quick response @mattgoldspink ...issue persists with node 14 as well.

Can you please let me know which combination of node/gulp/python versions worked for you,
[2021-05-13T11_16_11_078Z-debug.log](https://github.com/vlocityinc/newport-design-system/files/6472110/2021-05-13T11_16_11_078Z-debug.log)

**Comment by mattgoldspink** [comment]
Can you try running `npm install --save node-sass@4.14` and then re-run `npm install`

Looking at the releases for Node-sass, it looks like they didn't add Node 14 support until 4.14.0 release: https://github.com/sass/node-sass/releases/tag/v4.14.0

Internally we're using Node 14, but since this internal release isn't yet published that the difference between why Node 14 is working for us and not you.

**Comment by kirankapila** [comment]
This helped. I am able to launch storybook

Thanks a lot.
