### ISSUE TITLE
Unable to create zip | Error in plugin "gulp-sass"

### ISSUE THREAD

**Issue by rajareddybellary** [vlocityinc/newport-design-system#47]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?
A bug where I am not able to build the project.

I have cloned the repository and installed all the dependencies.

I tried npm start which runs the storybook.

But, when I try to build the project using the command

_npm run build && npm run dist_

It throws me the following error

[
<img width="841" alt="Screenshot 2021-12-09 at 5 13 09 PM" src="https://user-images.githubusercontent.com/78783271/145390453-07cf692b-fd33-4ad3-8429-d6ab70a9d32f.png">
](url)

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Build process 

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

> What steps and/or code are needed to reproduce this issue?

Clone the master branch, install dependencies and try to build the project using
_npm run build && npm run dist_

> What did you expect to happen?
It should create a dist folder with a zip

> What actually happened?
It threw an error in the command line saying

Error in plugin "gulp-sass"
Message:

gulp-sass 5 does not have a default Sass compiler; please set one yourself.

**Comment by mgoldspink-salesforce** [comment]
fixed in master
